/* 002 */
IF (NOT EXISTS (SELECT * 
                 FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_NAME = 'ISO_3166_2'))
BEGIN
  CREATE TABLE ISO_3166_2 (
      Code    CHAR(2) NOT NULL,
      Name    NVARCHAR(1024) NOT NULL
  )
END
