/* 003 */
TRUNCATE TABLE ISO_3166_2;

INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AF','Afghanistan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AX','Åland Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AL','Albania')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DZ','Algeria')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AS','American Samoa')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AD','Andorra')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AO','Angola')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AI','Anguilla')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AQ','Antarctica')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AG','Antigua and Barbuda')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AR','Argentina')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AM','Armenia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AW','Aruba')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AU','Australia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AT','Austria')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AZ','Azerbaijan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BS','Bahamas')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BH','Bahrain')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BD','Bangladesh')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BB','Barbados')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BY','Belarus')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BE','Belgium')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BZ','Belize')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BJ','Benin')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BM','Bermuda')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BT','Bhutan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BO','Bolivia, Plurinational State of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BQ','Bonaire, Sint Eustatius and Saba')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BA','Bosnia and Herzegovina')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BW','Botswana')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BV','Bouvet Island')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BR','Brazil')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IO','British Indian Ocean Territory')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BN','Brunei Darussalam')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BG','Bulgaria')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BF','Burkina Faso')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BI','Burundi')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KH','Cambodia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CM','Cameroon')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CA','Canada')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CV','Cape Verde')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KY','Cayman Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CF','Central African Republic')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TD','Chad')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CL','Chile')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CN','China')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CX','Christmas Island')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CC','Cocos (Keeling) Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CO','Colombia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KM','Comoros')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CG','Congo')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CD','Congo, the Democratic Republic of the')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CK','Cook Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CR','Costa Rica')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CI','Côte d’Ivoire')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HR','Croatia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CU','Cuba')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CW','Curaçao')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CY','Cyprus')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CZ','Czech Republic')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DK','Denmark')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DJ','Djibouti')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DM','Dominica')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DO','Dominican Republic')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('EC','Ecuador')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('EG','Egypt')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SV','El Salvador')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GQ','Equatorial Guinea')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ER','Eritrea')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('EE','Estonia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ET','Ethiopia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FK','Falkland Islands (Malvinas)')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FO','Faroe Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FJ','Fiji')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FI','Finland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FR','France')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GF','French Guiana')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PF','French Polynesia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TF','French Southern Territories')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GA','Gabon')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GM','Gambia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GE','Georgia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('DE','Germany')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GH','Ghana')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GI','Gibraltar')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GR','Greece')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GL','Greenland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GD','Grenada')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GP','Guadeloupe')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GU','Guam')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GT','Guatemala')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GG','Guernsey')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GN','Guinea')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GW','Guinea-Bissau')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GY','Guyana')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HT','Haiti')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HM','Heard Island and McDonald Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VA','Holy See (Vatican City State)')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HN','Honduras')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HK','Hong Kong')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('HU','Hungary')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IS','Iceland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IN','India')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ID','Indonesia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IR','Iran, Islamic Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IQ','Iraq')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IE','Ireland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IM','Isle of Man')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IL','Israel')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('IT','Italy')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('JM','Jamaica')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('JP','Japan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('JE','Jersey')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('JO','Jordan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KZ','Kazakhstan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KE','Kenya')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KI','Kiribati')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KP','Korea, Democratic People’s Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KR','Korea, Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KW','Kuwait')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KG','Kyrgyzstan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LA','Lao People’s Democratic Republic')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LV','Latvia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LB','Lebanon')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LS','Lesotho')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LR','Liberia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LY','Libya')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LI','Liechtenstein')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LT','Lithuania')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LU','Luxembourg')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MO','Macao')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MK','Macedonia, the Former Yugoslav Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MG','Madagascar')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MW','Malawi')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MY','Malaysia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MV','Maldives')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ML','Mali')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MT','Malta')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MH','Marshall Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MQ','Martinique')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MR','Mauritania')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MU','Mauritius')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('YT','Mayotte')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MX','Mexico')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('FM','Micronesia, Federated States of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MD','Moldova, Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MC','Monaco')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MN','Mongolia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ME','Montenegro')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MS','Montserrat')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MA','Morocco')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MZ','Mozambique')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MM','Myanmar')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NA','Namibia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NR','Nauru')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NP','Nepal')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NL','Netherlands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NC','New Caledonia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NZ','New Zealand')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NI','Nicaragua')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NE','Niger')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NG','Nigeria')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NU','Niue')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NF','Norfolk Island')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MP','Northern Mariana Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('NO','Norway')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('OM','Oman')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PK','Pakistan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PW','Palau')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PS','Palestine, State of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PA','Panama')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PG','Papua New Guinea')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PY','Paraguay')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PE','Peru')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PH','Philippines')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PN','Pitcairn')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PL','Poland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PT','Portugal')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PR','Puerto Rico')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('QA','Qatar')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('RE','Réunion')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('RO','Romania')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('RU','Russian Federation')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('RW','Rwanda')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('BL','Saint Barthélemy')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SH','Saint Helena, Ascension and Tristan da Cunha')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('KN','Saint Kitts and Nevis')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LC','Saint Lucia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('MF','Saint Martin (French part)')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('PM','Saint Pierre and Miquelon')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VC','Saint Vincent and the Grenadines')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('WS','Samoa')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SM','San Marino')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ST','Sao Tome and Principe')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SA','Saudi Arabia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SN','Senegal')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('RS','Serbia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SC','Seychelles')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SL','Sierra Leone')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SG','Singapore')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SX','Sint Maarten (Dutch part)')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SK','Slovakia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SI','Slovenia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SB','Solomon Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SO','Somalia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ZA','South Africa')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GS','South Georgia and the South Sandwich Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SS','South Sudan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ES','Spain')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('LK','Sri Lanka')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SD','Sudan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SR','Suriname')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SJ','Svalbard and Jan Mayen')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SZ','Swaziland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SE','Sweden')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('CH','Switzerland')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('SY','Syrian Arab Republic')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TW','Taiwan, Province of China')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TJ','Tajikistan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TZ','Tanzania, United Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TH','Thailand')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TL','Timor-Leste')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TG','Togo')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TK','Tokelau')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TO','Tonga')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TT','Trinidad and Tobago')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TN','Tunisia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TR','Turkey')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TM','Turkmenistan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TC','Turks and Caicos Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('TV','Tuvalu')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('UG','Uganda')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('UA','Ukraine')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('AE','United Arab Emirates')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('GB','United Kingdom')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('US','United States')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('UM','United States Minor Outlying Islands')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('UY','Uruguay')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('UZ','Uzbekistan')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VU','Vanuatu')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VE','Venezuela, Bolivarian Republic of')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VN','Viet Nam')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VG','Virgin Islands, British')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('VI','Virgin Islands, U.S.')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('WF','Wallis and Futuna')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('EH','Western Sahara')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('YE','Yemen')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ZM','Zambia')
INSERT INTO ISO_3166_2 (Code,Name) VALUES ('ZW','Zimbabwe')